### PR TITLE
Add `Solarized` theme

### PR DESCRIPTION
**Pull request by menelaos**

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much!

**Comment by hferreiro** [comment]
@menelaos I have been using https://github.com/seebi/dircolors-solarized and noticed that the colors are a bit different. Didn't you use that as a source?

**Comment by menelaos** [comment]
@hferreiro Good point, I used the standard values from `dircolors` in [`coreutils`](https://www.gnu.org/software/coreutils/). They are indeed slightly different from the link above but I feel they are more consistent and easier on the eye. Have you tried to use them for a few days? Let me know what you think :-)

**Comment by hferreiro** [comment]
My first impression is the opposite, though I guess that's really subjective. My main issue is that directories seems to be bold and well-known extensions (e.g. .md, .py, .cc, .h) aren't highlighted. You can compare them here (the second one is from your theme):
Screenshot from 2020-04-25 00-32-25
seebi

**Comment by menelaos** [comment]
Yes, you are right, it is a matter of preference in the end. I also used [seebi/dircolors-solarized](https://github.com/seebi/dircolors-solarized) before so I feel where you are coming from.

Ultimately, I decided to follow `coreutils` and use the standard `dircolors` color scheme as it is more widely established. As I've already mentioned, I have since come to prefer it. Given that `dircolors-solarized` was never merged into the official `solarized` repo, I don't think it can be considered "official".

To address at least your second issue a little bit: The [solarized](https://ethanschoonover.com/solarized/) page recommends `base00` (light theme) and `base0` (dark theme) for "primary content". I would argue that on the command line, almost all text files, whether it be source files or your grocery shopping list, are "primary content". 
With [seebi/dircolors-solarized](https://github.com/seebi/dircolors-solarized) you would often end up with lots of colors but very little "primary content".

**Pull request merged**
