### PR TITLE
Add remaining core filetypes

### PR DESCRIPTION
**Pull request by gseidler**
Reorder core filetypes according to dircolors database as displayed by:
    dircolors --print-database
Add work-in-progress gruvbox-dark theme to test new filetypes

### CODE REVIEW

**Comment by gseidler** [comment]
The other themes probably need updating. I guess there is a branch with that goal already.

**Comment by sharkdp** [comment]
Thank you very much!

Yes - we would need to update the other themes.

**Comment by ixti** [comment]
When this might become available in master branch?

**Comment by ixti** [comment]
Would be also nice to see dracula theme as well :D

**Comment by sharkdp** [comment]
when someone decides to put in the required work to update all other themes.

**Comment by ixti** [comment]
@sharkdp I've opened 2 PRs one with coretypes and themes updates, and the other with gruvbox theme files themeselves.

**Review by Hk00998877 — APPROVED** [review]
#80

**Review by Hk00998877 — APPROVED** [review]

**Pull request closed without merging**
