### PR TITLE
Add iceberg theme

### PR DESCRIPTION
**Pull request by p00f**
The colors are taken from the [terminal port](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/wezterm/iceberg-dark.toml) of the [iceberg vim colorscheme](https://cocopon.github.io/iceberg.vim/)

The rest of the file is the same as one-dark.yml

### CODE REVIEW

**Comment by p00f** [comment]
image

**Comment by p00f** [comment]
image

**Comment by p00f** [comment]
image

**Comment by p00f** [comment]
image

**Comment by sharkdp** [comment]
Cool - Thank you very much for your contribution!

**Comment by sharkdp** [comment]
Released in [v0.8.0](https://github.com/sharkdp/vivid/releases/tag/v0.8.0).

**Pull request merged**
