### PR TITLE
Dracula theme

### PR DESCRIPTION
**Pull request by yavko**
# dracula support
thats it

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much. I would like to merge #78 first. This theme would then need a small update similar to the ones done for other themes in #78.

**Comment by yavko** [comment]
> Thank you very much. I would like to merge #78 first. This theme would then need a small update similar to the ones done for other themes in #78.

Sounds good!

**Comment by sharkdp** [comment]
#78 has been merged now. It would be great if you could make the necessary changes here.

**Comment by yavko** [comment]
> #78 has been merged now. It would be great if you could make the necessary changes here.

yup time to port

**Comment by yavko** [comment]
COMPLETE :)

**Comment by yavko** [comment]
I also added some changes to make it match the dracula colorls theme better since that is the only official theme that could maybe apply here: https://github.com/dracula/colorls/blob/master/dark_colors.yaml

**Comment by azzamsa** [comment]
@yavko Thanks for the hard work. Waiting it to be merged into master.

**Comment by sharkdp** [comment]
Thank you very much!

**Comment by sharkdp** [comment]
Released in [v0.8.0](https://github.com/sharkdp/vivid/releases/tag/v0.8.0).

**Comment by yavko** [comment]
> Released in [v0.8.0](https://github.com/sharkdp/vivid/releases/tag/v0.8.0).

yay

**Pull request merged**
